name: Container

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

# avoid races when pushing containers built from main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push container
        uses: coreos/actions-lib/build-container@main
        with:
          credentials: ${{ secrets.QUAY_AUTH }}
          file: dist/Dockerfile
          push: quay.io/coreos/airlock
          # Speed up PR CI by skipping arm64
          pr-arches: amd64
